#!/bin/bash -eux
: ${K8S_SU_USER:=coopadmin}
: ${KEYER:=https://raw.githubusercontent.com/WebHostingCoopTeam/keys/master/myaddus.sh}

TMP=$(mktemp -d)
cd $TMP

# Keyer
curl -o $TMP/keyer $KEYER
chmod 555 $TMP/keyer
bash $TMP/keyer

useradd $K8S_SU_USER
mkdir -p /home/$K8S_SU_USER
chown -R $K8S_SU_USER. /home/$K8S_SU_USER
chown -R $K8S_SU_USER. $TMP
chmod 777 $TMP
sudo -u $K8S_SU_USER ls -lh $TMP
sudo -u $K8S_SU_USER bash $TMP/keyer

cat << EOF > /usr/local/bin/get-ip-address
#!/bin/bash
echo -n 'IP address = '
/sbin/ifconfig | grep "inet addr" | grep -v "127.0.0.1" | awk '{ print \$2 }' | awk -F: '{ print \$2 }'
echo -n 'SSH '
grep Port /etc/ssh/sshd_config 
EOF

chmod +x /usr/local/bin/get-ip-address

cat << EOF > /etc/network/if-up.d/show-ip-address
#!/bin/sh
if [ "\$METHOD" = loopback ]; then
    exit 0
fi

# Only run from ifup.
if [ "\$MODE" != start ]; then
    exit 0
fi

cp /etc/issue-standard /etc/issue
/usr/local/bin/get-ip-address >> /etc/issue
echo "" >> /etc/issue
EOF

chmod +x /etc/network/if-up.d/show-ip-address

rm -Rf $TMP
