#!/bin/sh -eux
TMP=$(mktemp -d)
PRE_INSTALL_PKGS='epel-release centos-release-openshift-origin'
INSTALL_PKGS='ansible socat python python-pip wget git net-tools bind-utils iptables-services bridge-utils bash-completion origin-clients kexec-tools sos psacct isci-initiator-utils'

cd $TMP
wget -cq https://github.com/joshuacox/kubash/raw/centos/pax/centos7-yum.repos.d.tgz
cd /etc
tar zxvpf $TMP/centos7-yum.repos.d.tgz
rm -v $TMP/centos7-yum.repos.d.tgz

yum clean all
yum update
curl https://raw.githubusercontent.com/joshuacox/roustabout/master/RHkubeNstall|bash
yum repolist enabled
yum install -y yum-utils

cd $TMP
wget -cq http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -ivh epel-release-latest-7.noarch.rpm
rm -v epel-release-latest-7.noarch.rpm

yum update

yum repolist enabled
yum-config-manager -enable base 
yum-config-manager -enable extras
yum-config-manager -enable updates
yum-config-manager -enable epel
yum repolist enabled

yum --enablerepo=extras install -y $PRE_INSTALL_PKGS
yum --enablerepo=extras,epel install -y $INSTALL_PKGS

pip install --upgrade pip


#edit /etc/sysconfig/docker file and add --insecure-registry 172.30.0.0/16 to the OPTIONS parameter.
sed -i '/OPTIONS=.*/c\OPTIONS="--selinux-enabled --insecure-registry 172.30.0.0/16"' \
  /etc/sysconfig/docker
systemctl is-active docker
systemctl enable docker
systemctl start docker

# remove temp
cd
rm -Rf $TMP
