stages:
  - build
  - test 
  - deploy 


image: "ruby:2.5"

before_script:
  - ruby -v
  - which ruby
  - pwd 

build_job:
  stage: build
  script:
    - echo 'build'

rspec:
  stage: test
  script:
    - echo 'rspec'

rubocop:
  stage: test
  script:
    - echo 'rubocop'

fulltest:
  stage: test
  tags:
    - fulltest
  only:
    - fulltest
  script:
    - git checkout fulltest
    - echo 'fulltest executed!'

deploy_job:
  stage: deploy
  script:
    - echo 'deploy'
