stages:
  - bootstrap
  - build
  - test 
  - deploy 

build_job:
  stage: bootstrap
  allow_failure: true
  script:
    - whoami
    - echo 'build'
    - bash -l .ci/ex.sh
    - curl -sL git.io/kubash > /tmp/kubash
    - chmod +x /tmp/kubash
    - yes y | /tmp/kubash
    - bash -l .ci/builder.sh

fulltest-bootstrap:
  stage: bootstrap
  tags:
    - fulltest
  only:
    - fulltest
  except:
    - merge_requests
  allow_failure: true
  script:
    - echo 'fulltest1bootstrap'
    - bash -l .ci/ex.sh
    - cd $HOME/.kubash && git pull && echo '/home/packer_cache/' > .packer_cache_path && cd pax && ./update_packer_cache 
    - curl -sL git.io/kubash > /tmp/kubash
    - chmod +x /tmp/kubash
    - yes y | /tmp/kubash

fulltest-build:
  stage: build
  tags:
    - fulltest
  only:
    - fulltest
  except:
    - merge_requests
  allow_failure: false
  script:
    - echo 'fulltest1build'
    - bash -l .ci/builder.sh

fulltest-test:
  stage: test
  tags:
    - fulltest
  only:
    - fulltest
  except:
    - merge_requests
  script:
    - whoami
    - echo 'fulltest1'
    - bash -l .ci/tester.sh

fulltest-deploy:
  stage: deploy
  tags:
    - fulltest
  only:
    - fulltest
  except:
    - merge_requests
  script:
    - echo 'fulltest1deploy'
    - ls
    - pwd

deploy_job:
  stage: deploy
  script:
    - echo 'deploy'
