matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      cache:
        directories:
        - $HOME/.minikube
        - $HOME/.kube
        - $HOME/.local/bin
        - .git
        - /usr/local
      env:
        - MINIKUBE_MEMORY=7777
        - MINIKUBE_CPU=4
        - MINIKUBE_DRIVER=none
        - HELM_INSTALL_DIR=$HOME/.local/bin
        - NVM_DIR="$HOME/.nvm"

language: node_js
node_js:
  - "8"

addons:
  apt:
    packages:
      - curl
      - rsync
      - socat
      - time
      - devscripts
      - ansible
      - parallel
      - golang
      - nmap
      - python-pip

before_install:
# install nsenter which is required for port forwarding
  - npm i -g yaml2json
  - ln -s $(pwd) /home/travis/.kubash
  - curl -sL --silent https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get|bash
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .ci/ubuntu-compile-nsenter.sh && sudo cp .tmp/util-linux-2.30.2/nsenter /usr/local/bin; fi
  - make bats
  - make ct

script:
  - bash scripts/dotfiles
  - bash scripts/chkdirs
  - sudo chown -R $USER /usr/local
  - sudo mkdir -p /etc/kubernetes
  - sudo chown -R $USER /etc/kubernetes
  - /bin/bash -l -c "/usr/bin/time -v make -e ci"
  - env
  - pwd
  - mkdir -p clusters/default
  - cp $HOME/.kube/config clusters/default/
  - /bin/bash -l -c "kubash openebs"
  - /bin/bash -l -c "kubash demo"
  - bats .tests.bats
  - w8s/generic.w8 percona default
  - w8s/generic.w8 pgset-0 default
  - w8s/generic.w8 rabbitmq-0 default
  - w8s/generic.w8 mongo-0 default
  #- w8s/generic.w8 pgset-1 default
  #- w8s/generic.w8 rabbitmq-1 default
  #- w8s/generic.w8 mongo-1 default
  #- w8s/generic.w8 rabbitmq-2 default
  #- w8s/generic.w8 mongo-2 default

