apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: $my_master_ip
$ENDPOINTS_LINES
networking:
  podSubnet: $my_KUBE_CIDR
apiServerCertSANs:
- $load_balancer_ip
apiServerExtraArgs:
  apiserver-count: "3"
