apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: $KUBERNETES_VERSION
networking:
  podSubnet: $my_KUBE_CIDR
api:
  advertiseAddress: $my_master_ip
apiServerCertSANs:
- 127.0.0.1
- $my_master_ip
- $load_balancer_ip
etcd:
$ENDPOINTS_LINES
apiServerExtraArgs:
  endpoint-reconciler-type: "lease"
