#!/bin/bash
set -eux

inst_kubedb_helm () {
  helm repo add appscode https://charts.appscode.com/stable/
  helm repo update
  helm install appscode/kubedb --name kubedb-operator --version 0.10.0 --namespace kube-system
  helm install appscode/kubedb-catalog --name kubedb-catalog --version 0.10.0 --namespace kube-system
}

main () {
  inst_kubedb_helm
}

main $@
